-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE school.refresh_tokens (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     user_id UUID REFERENCES school.users(id) ON DELETE CASCADE,
--     token TEXT NOT NULL,
--     expires_at TIMESTAMP NOT NULL,
--     is_revoked BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP DEFAULT now()
-- );
